// initialState.js
export const emptyContractState = {
  name: "",
  type: "تصميم",
  status: "مسودة",
  date: new Date().toISOString().split("T")[0],
  dueDate: "",
  partyA: "",
  partyB: "",
  partyADetails: {
    representant: "",
    cr: "",
    address: "",
    capacity: "الطرف الأول",
  },
  partyBDetails: {
    representant: "",
    idNumber: "",
    address: "",
    phone: "",
    email: "",
    capacity: "الطرف الثاني",
  },
  projectDetails: {
    name: "",
    location: "",
    city: "",
    deedNumber: "",
    plotNumber: "",
  },
  financials: { taxAmount: 0, grandTotal: 0, advancePayment: 0 },
  contractValue: 0,
  paymentTerms: "",
  scope: [],
  obligationsList: [],
  terms: "",
  specialTerms: "",
  generalConditions: "",
  governingLaw:
    "يخضع هذا العقد للأنظمة والقوانين المعمول بها في المملكة العربية السعودية.",
  witnesses: [
    { name: "", id: "" },
    { name: "", id: "" },
  ],
  version: 1,
  approvalMethod: "platform",
  introduction: "",
  coverSummary: "",
  aiSummary: "",
  aiRiskAssessment: "",
  isOnePageSummary: false,
  activePresets: [],
  coverSettings: {
    showLogo: true,
    showSummary: true,
    subtitle: "",
    version: "1.0",
    background: { opacity: 0.1, size: "cover", applyTo: "all", imageUrl: "" },
  },
  verificationSettings: {
    allowPublicVerification: true,
    showParties: false,
    showFinancials: false,
    allowDownload: false,
    customErrorMessage: "عفواً، لا تملك صلاحية لعرض تفاصيل هذا العقد.",
  },
  qrSettings: {
    enabled: true,
    projectLocationUrl: "",
    frontQrContent: "link",
    backQrContent: "both",
  },
  frameSettings: {
    pageFrame: {
      enabled: true,
      style: "solid",
      color: "#e2e8f0",
      margin: "20px",
    },
    frontCoverFrame: {
      enabled: true,
      style: "double",
      color: "#0f172a",
      margin: "30px",
    },
    backCoverFrame: {
      enabled: true,
      style: "solid",
      color: "#065f46",
      margin: "30px",
    },
  },
  spacingSettings: {
    lineHeight: "1.8",
    paragraphSpacing: "16px",
    padding: "40px",
  },
  typographySettings: {
    fontFamily: "Tajawal",
    fontSize: "14px",
    color: "#0f172a",
  },
};
