import {
  LayoutDashboard,
  Users,
  FileText,
  FolderOpen,
  Wallet,
  Building2,
  Handshake,
  Map as MapIcon,
  BarChart3,
  ScrollText,
  Laptop,
  Award,
  Settings,
  FileSliders,
  Zap,
  MessageCircle,
} from "lucide-react";

export const DEFAULT_MENU_CATEGORIES = [
  {
    id: "CAT_DASHBOARD",
    title: "الشاشة الحالية: الرئيسية",
    icon: LayoutDashboard,
    isMain: true,
    items: [
      { id: "01", label: "لوحة التحكم الرئيسية", code: "SCR_01_VIEW" },
      { id: "02", label: "التنبيهات", code: "SCR_02_VIEW" },
      { id: "109", label: "الروابط السريعه", code: "SCR_109_VIEW" },
      { id: "03", label: "المهام", code: "SCR_03_VIEW" },
      { id: "030", label: "مفكره المكتب", code: "SCR_030_VIEW" },
      { id: "04", label: "الإحصائيات السريعة", code: "SCR_04_VIEW" },
    ],
  },
  {
    id: "CAT_TRANSACTIONS",
    title: "إدارة المعاملات",
    icon: FileText,
    items: [
      { id: "10", label: "المعاملات", code: "SCR_10_VIEW", isFavorite: true },
      {
        id: "815",
        label: "عروض الأسعار",
        code: "SCREEN_815_VIEW",
        isFavorite: true,
      },
      {
        id: "11",
        label: "أرشيف المشاريع",
        code: "SCR_11_VIEW",
        isFavorite: true,
      },
      {
        id: "12",
        label: "متابعة المعاملات",
        code: "SCR_12_VIEW",
        isFavorite: true,
      },
      {
        id: "13",
        label: "سجل حالات المعاملات",
        code: "SCR_13_VIEW",
        isFavorite: true,
      },
      { id: "14", label: "أنواع المعاملات", code: "SCR_14_VIEW" },
      { id: "15", label: "إعدادات المعاملات", code: "SCR_15_VIEW" },
    ],
  },
  {
    id: "CAT_CLIENTS",
    title: "العملاء والملكية",
    icon: Users,
    items: [
      { id: "300", label: "العملاء", code: "SCREEN_300_VIEW" },
      { id: "310", label: "ملفات الملكية", code: "SCREEN_310_VIEW" },
      { id: "07", label: "الصكوك", code: "SCR_07_VIEW" },
      { id: "222", label: "تعاقدات العملاء", code: "SCR_222_VIEW" },
      { id: "08", label: "الهويات", code: "SCR_08_VIEW" },
      { id: "09", label: "سجلات الرخص الخارجية", code: "SCR_09_VIEW" },
      { id: "0010", label: "سجلات رخص مكتبنا", code: "SCR_0010_VIEW" },
      {
        id: "112",
        label: "اشتراطات و أدلة و تعاميم و عروض",
        code: "SCR_112_VIEW",
      },
    ],
  },
  {
    id: "CAT_DOCS",
    title: "المستندات",
    icon: FolderOpen,
    items: [
      { id: "16", label: "مركز المستندات", code: "SCR_16_VIEW" },
      { id: "17", label: "أنواع المستندات", code: "SCR_17_VIEW" },
      { id: "170", label: "العقود", code: "SCR_170_VIEW" },
      { id: "18", label: "نماذج الجهات الرسمية", code: "SCR_18_VIEW" },
      { id: "19", label: "مركز تجهيز الملفات", code: "SCR_19_VIEW" },
      { id: "20", label: "التوثيق الإلكتروني", code: "SCR_20_VIEW" },
      { id: "21", label: "الملفات المؤرشفة", code: "SCR_21_VIEW" },
      { id: "90", label: "أرشيف المخططات", code: "SCR_90_VIEW" },
      { id: "91", label: "محاضر اجتماعات العميل", code: "SCR_91_VIEW" },
    ],
  },
  {
    id: "CAT_FINANCE",
    title: "العمليات المالية",
    icon: Wallet,
    items: [
      { id: "23", label: "المالية (الشاشة الموحدة)", code: "SCR_23_VIEW" },
      { id: "24", label: "الفواتير", code: "SCR_24_VIEW" },
      { id: "25", label: "التسويات", code: "SCR_25_VIEW" },
      { id: "26", label: "إعدادات المالية", code: "SCR_26_VIEW" },
      { id: "27", label: "الحسابات المرتبطة", code: "SCR_27_VIEW" },
      { id: "28", label: "الإيرادات والمصروفات", code: "SCR_28_VIEW" },
    ],
  },
  {
    id: "CAT_HR_TOOLS",
    title: "الموارد البشرية",
    icon: Zap,
    items: [{ id: "88", label: "إدارة الموارد البشرية", code: "SCR_88_VIEW" }],
  },
  {
    id: "EMAIL_SETTINGS",
    title: "الايميل و الرسائل",
    icon: MessageCircle,
    items: [
      { id: "98", label: "مركز الإشعارات", code: "SCR_98_VIEW" },
      { id: "99", label: "الصادر و الوارد", code: "SCR_99_VIEW" },
      { id: "100", label: "مركز طلب و إرسال الوثائق", code: "SCR_100_VIEW" },
      { id: "101", label: "اعدادات الايميل", code: "SCR_101_VIEW" },
    ],
  },
  {
    id: "CAT_ACCOUNTING_PORTAL",
    title: "بوابة المحاسبة",
    icon: Building2,
    items: [{ id: "29", label: "بوابة شركة المحاسبة", code: "SCR_29_VIEW" }],
  },
  {
    id: "CAT_BROKERS",
    title: "الوسطاء والشركاء",
    icon: Handshake,
    items: [
      { id: "30", label: "الوسطاء", code: "SCR_30_VIEW" },
      { id: "31", label: "المكاتب الوسيطة", code: "SCR_31_VIEW" },
      { id: "32", label: "الشركاء", code: "SCR_32_VIEW" },
      { id: "33", label: "اتفاقيات الشراكة", code: "SCR_33_VIEW" },
    ],
  },
  {
    id: "CAT_RIYADH",
    title: "تقسيم مدينة الرياض",
    icon: MapIcon,
    items: [
      { id: "39", label: "تقسيم الرياض", code: "SCR_39_VIEW" },
      { id: "40", label: "القطاعات", code: "SCR_40_VIEW" },
      { id: "41", label: "الأحياء", code: "SCR_41_VIEW" },
    ],
  },
  {
    id: "CAT_REPORTS",
    title: "التقارير",
    icon: BarChart3,
    items: [
      { id: "42", label: "التقارير العامة", code: "SCR_42_VIEW" },
      { id: "43", label: "تقارير المعاملات", code: "SCR_43_VIEW" },
      { id: "44", label: "تقارير المالية", code: "SCR_44_VIEW" },
      { id: "45", label: "تقارير الموظفين", code: "SCR_45_VIEW" },
      { id: "46", label: "تقارير العملاء", code: "SCR_46_VIEW" },
      { id: "47", label: "تقارير المستندات", code: "SCR_47_VIEW" },
    ],
  },
  {
    id: "CAT_LOGS",
    title: "سجلات النظام",
    icon: ScrollText,
    items: [
      { id: "48", label: "سجلات النظام الشاملة", code: "SCR_48_VIEW" },
      { id: "49", label: "سجل الجلسات", code: "SCR_49_VIEW" },
      { id: "50", label: "سجل العمليات", code: "SCR_50_VIEW" },
      { id: "51", label: "سجل الطباعة", code: "SCR_51_VIEW" },
      { id: "52", label: "سجل الذكاء الصناعي", code: "SCR_52_VIEW" },
    ],
  },
  {
    id: "CAT_ASSETS",
    title: "أصول المكتب",
    icon: Laptop,
    items: [
      { id: "58", label: "أصول المكتب", code: "SCR_58_VIEW" },
      { id: "59", label: "الأجهزة", code: "SCR_59_VIEW" },
      { id: "60", label: "البرمجيات", code: "SCR_60_VIEW" },
      { id: "61", label: "التراخيص", code: "SCR_61_VIEW" },
      { id: "62", label: "فواتير الأصول", code: "SCR_62_VIEW" },
      { id: "63", label: "تنبيهات الأصول", code: "SCR_63_VIEW" },
    ],
  },
  {
    id: "CAT_QUALIFICATION",
    title: "تأهيل المكتب",
    icon: Award,
    items: [
      { id: "64", label: "التأهيل لدى الجهات", code: "SCR_64_VIEW" },
      { id: "65", label: "الجهات الحكومية", code: "SCR_65_VIEW" },
      { id: "66", label: "ملفات التأهيل", code: "SCR_66_VIEW" },
    ],
  },
  {
    id: "CAT_SYS_SETTINGS",
    title: "إدارة النظام",
    icon: Settings,
    items: [{ id: "71", label: "إعدادات النظام", code: "SCR_71_VIEW" }],
  },
  {
    id: "CAT_REPORT_SETTINGS",
    title: "إعدادات التقارير",
    icon: FileSliders,
    items: [
      { id: "76", label: "ترميز التقارير", code: "SCR_76_VIEW" },
      { id: "77", label: "تكويد التقارير", code: "SCR_77_VIEW" },
      { id: "78", label: "التوقيع الرقمي", code: "SCR_78_VIEW" },
      { id: "79", label: "تشفير التقارير", code: "SCR_79_VIEW" },
    ],
  },
];
